apiVersion: v1
kind: Service
metadata:
  name: iweb-lens
  labels:
    app:  iweb-lens
spec:
  selector:
    app:  iweb-lens
  type: NodePort
  ports:
  - protocol:  tcp
    nodePort: 30005
    port: 5000
    targetPort: 5000